"""Copy the five architecture diagrams and replace Chinese labels with English.

Run from repo root: python scripts/translate-diagrams.py
Writes docs/img/*.en.drawio.svg. Does not touch the Chinese originals.
"""
from __future__ import annotations

import html
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "docs" / "img"

# Longest first. Applied to the whole file so visible <text> and mxGraph
# content= stay in lockstep.
PAIRS: list[tuple[str, str]] = [
    ("两栈相加最多留 20 版，超了从最旧的 undo 开始裁；一旦有新快照入栈，redo 栈整个清空。回退是整篇回退，不是只撤选区。",
     "Both stacks keep 20 versions total; oldest undo is dropped first. A new snapshot clears redo. Rollback is the whole note, not just the selection."),
    ("18 个旋钮，TS 的 LIMIT_SPEC 与 config.py 的 LIMIT_RANGE 由 npm test 逐项比对。",
     "18 knobs: LIMIT_SPEC in TS and LIMIT_RANGE in config.py are compared by npm test."),
    ("设置项只夹紧，不报错——一个填错的数字绝不能把你这一轮对话弄挂。",
     "Settings clamp, they never error — a bad number must not kill this turn."),
    ("读者正在读的那一轮不受影响——深挖全程在另一条线程上，超支也只掐它自己。",
     "The turn you are reading is untouched — deep-dive is another thread; overspend only kills itself."),
    ("磁盘一个字节没动，模型收到一句「读者没同意」",
     "disk unchanged; the model is told the reader said no"),
    ("0 不是保守，是回归保证：不填任何东西，行为和上限上线前逐字节一致。",
     "0 is not conservative: it is the regression guarantee. Leave them blank and behaviour matches the pre-cap build byte for byte."),
    ("撞线时不执行那一批工具，但收口那一枪照打——不然已花的钱全扔了。",
     "On the cap, that tool batch is skipped, but the closing shot still fires — otherwise the spend is wasted."),
    ("「别再翻别的教材，用已经读到的作答，并告诉读者你只读了哪几段。」",
     "Stop reading other books. Answer from what you have, and say which passages you saw."),
    ("唯一出网的那条线，是你自己在设置页里填的模型节点。",
     "The only outbound path is the model endpoint you fill in on the settings page."),
    ("模型提得出编辑，落不了盘——落盘那一下永远是你按的。",
     "The model can propose an edit. It cannot land it — you always press that key."),
    ("SSE 一共八种事件：status · think · token · tool · approval · spend · done · error。",
     "Eight SSE events: status · think · token · tool · approval · spend · done · error."),
    ("主对话 · 后台深挖 · 跨书翻页。后台超支，掐不到你正在读的那轮。",
     "Main chat · deep-dive · cross-book. Overspend on deep-dive cannot kill the turn you are in."),
    ("空会话 1 天 · 聊过的 7 天 · 挂着审批的 30 天，启动时清一次。",
     "Empty sessions: 1 day · chatted: 7 days · pending approval: 30 days. Purged on start."),
    ("插件拉起它时只接受 127.0.0.1 / localhost / ::1，别的地址当场 not-loopback。",
     "When the plugin starts it, only 127.0.0.1 / localhost / ::1; anything else is not-loopback."),
    ("写只允许登记过的那一篇；读可放宽到白名单。.git · .obsidian · .env* 一律拒。",
     "Write: only the registered note. Read: may widen to a whitelist. .git · .obsidian · .env* refused."),
    ("read_file → allow 自动过；edit_file → ask 每次问人；其他名字 → deny。",
     "read_file → allow; fetch → allow; edit_file → ask every time; any other name → deny."),
    ("要改哪一段，必须更早一轮真读过那个文件。同批 read+edit 也拦。",
     "To edit a passage, an earlier turn must have really read that file. Same-batch read+edit is blocked too."),
    ("落盘那一下永远是你按的。点「不允许」时磁盘一个字节都没动。",
     "Landing on disk is always your click. Deny: not one byte moves."),
    ("会话 · 快照 · 配额 · 深挖题全在本机；唯一出网的是你自己填的模型节点。",
     "Sessions · snapshots · quotas · deep questions stay on this machine; outbound is only your model endpoint."),
    ("本场最多 8 次 · 每小时最多 40 次 · 并发 2 · 待答积压满 3 就停。",
     "8 per session · 40 per hour · concurrency 2 · stop when 3 sit unanswered."),
    ("一轮最多 24 000 字符 / 8 次；工具轮上限 100 轮。",
     "24,000 characters / 8 reads per turn; tool-loop cap 100."),
    ("快照入栈（undo+redo 共留 20 版）→ 写盘 → 续跑",
     "snapshot (undo+redo keep 20) → write disk → continue"),
    ("拼 messages[0]：这本书的书名 + 选区 + 邻域",
     "build messages[0]: book title + selection + neighborhood"),
    ("本地读 → 回填 → 再问一次（工具轮上限 100）",
     "local read → fill → ask again (tool-loop cap 100)"),
    ("read-first 硬闸：更早一轮没真读过这个文件 → 当场拒",
     "read-first gate: no earlier real read of this file → refuse now"),
    ("done 那一刻，深挖 daemon 才起跑 → 见下一张图",
     "only when done does the deep-dive daemon start → next figure"),
    ("写回：两把工具，三道闸，一个快照栈",
     "Write-back: three tools, three gates, one snapshot stack"),
    ("闸门全景：钱一套闸，安全另一套",
     "All the gates: one set for money, another for safety"),
    ("三个进程，一条 loopback",
     "Three processes, one loopback"),
    ("一轮对话：从划词到落字",
     "One turn: from highlight to written word"),
    ("后台深挖：一条任务队列",
     "Background deep-dive: a job queue"),
    ("成本闸 · 分类不分总，默认全关",
     "Cost gates · per kind, not a total; all off by default"),
    ("安全闸 · 能不能，不由模型说了算",
     "Safety gates · whether it may, the model does not decide"),
    ("三个 token 闸，各记各的账",
     "Three token gates, each with its own ledger"),
    ("默认三个全是 0 = 不限",
     "All three default to 0 = unlimited"),
    ("⚠️ 主对话那个不是硬上限",
     "⚠️ the main-chat cap is not hard"),
    ("撞线不报错，只递一句话给模型",
     "Hitting the cap is not an error; one sentence goes to the model"),
    ("深挖的次数闸",
     "Deep-dive count gates"),
    ("跨书翻页的字数闸",
     "Cross-book character gate"),
    ("会话会过期，账也会跟着掉",
     "Sessions expire; the ledger goes with them"),
    ("sidecar 只认 loopback",
     "sidecar only binds loopback"),
    ("沙箱两套根",
     "Sandbox: two sets of roots"),
    ("权限三值，没有第四种",
     "Permissions are three-valued, no fourth"),
    ("read-first 硬闸",
     "read-first hard gate"),
    ("审批闸",
     "Approval gate"),
    ("数据不出 .pen",
     "Data does not leave .pen"),
    ("前后端两张限值表不许漂",
     "The two limit tables must not drift"),
    ("十条否决理由，命中一条就不探：",
     "Ten vetoes; any one skips the probe:"),
    ("关了 · 没配模型 · 这轮出错 · 挂着审批",
     "off · no model · this turn errored · approval pending"),
    ("search / writeback 芯片 · 回复 ≤ 80 字",
     "search / writeback chips · reply ≤ 80 chars"),
    ("锚落在封面或附录 · 轮次冷却",
     "anchor on cover or appendix · turn cooldown"),
    ("本场配额用完 · 待答积压满",
     "session quota used up · unanswered queue full"),
    ("刻意不用 ThreadPoolExecutor：",
     "Deliberately no ThreadPoolExecutor:"),
    ("它注册 atexit join，一个卡住的",
     "it registers atexit join; one stuck"),
    ("worker 会让 Ctrl-C 停 30 秒。",
     "worker makes Ctrl-C wait 30s."),
    ("故意不喂邻域：邻域里全是教材",
     "Deliberately no neighborhood: it is full of"),
    ("自带的入门题，喂了必产同构题。",
     "the handbook beginner drills — feed it and you get clones."),
    ("给的是目录 + 题面 + 本轮问答。",
     "What it gets: contents + questions + this turn Q and A."),
    ("永不给它 tools。广度由代码封死，",
     "Never give it tools. Breadth is sealed in code,"),
    ("不由模型自律：最多 2 段 × 80 行，",
     "not by model self-control: at most 2 passages x 80 lines,"),
    ("最多读 2 次。",
     "at most 2 reads."),
    ("五条轴，每条各有硬校验：",
     "Five axes, each with a hard check:"),
    ("bridge 搭桥 · tradeoff 权衡 · vs_real 对出身",
     "bridge · tradeoff · vs_real (origins)"),
    ("failure 失效 · altitude 换层",
     "failure · altitude"),
    ("槽位 + 锚点校验不过 → 丢",
     "slot + anchor check fails → drop"),
    ("grounding=open 每轮只放 1 条",
     "grounding=open: at most 1 per turn"),
    ("相似度 ≥ 0.72 去重（本轮 + 本场已问）",
     "similarity ≥ 0.72 dedupes (this turn + already asked)"),
    ("每轮最多留 2 条",
     "keep at most 2 per turn"),
    ("timing=now → 当场抛给读者",
     "timing=now → ask the reader now"),
    ("timing=later → 留池子里，下轮重新过闸",
     "timing=later → stay in the pool, re-gated next turn"),
    ("3 秒一拍，最多 8 分钟，",
     "one beat every 3s, at most 8 minutes,"),
    ("连失败 3 次放弃。",
     "give up after 3 failures in a row."),
    ("running 一空就停。",
     "stop as soon as running is empty."),
    ("主对话这一轮 done",
     "main chat turn: done"),
    ("触发闸 should_probe",
     "trigger gate should_probe"),
    ("纯同步、零成本，不花一分钱",
     "sync, zero cost, spends nothing"),
    ("daemon 线程起跑",
     "daemon thread starts"),
    ("拼 probe 的 system + user",
     "build probe system + user"),
    ("定向读：由 Python 执行",
     "directed read: Python executes it"),
    ("问模型：强制填槽，一次最多 3 条候选",
     "ask the model: force slots, at most 3 candidates"),
    ("收割闸链",
     "harvest gate chain"),
    ("代码验槽，不验措辞",
     "code checks slots, not wording"),
    ("投进收件箱：会话为键 + 一个游标",
     "into the inbox: session key + a cursor"),
    ("侧栏拉走 → ◆ 深挖芯片冒出来",
     "sidebar fetches → ◆ deep-dive chip appears"),
    ("depth &lt; 4 → 丢",
     "depth &lt; 4 → drop"),
    ("depth < 4 → 丢",
     "depth < 4 → drop"),
    ("芯片 · 选区 · 你的问题 · 你的设置",
     "chip · selection · your question · your settings"),
    ("messages + 两把工具的 JSON schema",
     "messages + JSON schema for three tools"),
    ("tool_call  read_file(教材, 940–1010 行)",
     "tool_call  read_file(handbook, lines 940–1010)"),
    ("正文，流式吐 token",
     "body, tokens streamed"),
    ("SSE token — 逐字上屏",
     "SSE token — painted as it arrives"),
    ("SSE approval — 整轮挂起",
     "SSE approval — the turn hangs"),
    ("磁盘一个字节都没动",
     "not one byte of disk moved"),
    ("Obsidian 侧栏",
     "Obsidian sidebar"),
    ("你填的模型节点",
     "the model endpoint you set"),
    ("sidecar · Python · FastAPI · 只绑 127.0.0.1",
     "sidecar · Python · FastAPI · loopback only"),
    ("只在两套根之内",
     "only inside the two roots"),
    ("Obsidian 插件 · TypeScript",
     "Obsidian plugin · TypeScript"),
    ("侧栏 · 设置页 · 拉起 sidecar",
     "sidebar · settings · starts sidecar"),
    ("app.py — 23 条 HTTP 路由",
     "app.py — 23 HTTP routes"),
    ("tutor.py — 消息循环 · 两把工具",
     "tutor.py — message loop · three tools"),
    ("probe.py — 深挖 daemon 线程",
     "probe.py — deep-dive daemon thread"),
    ("会话 · 快照 · 每小时配额 · 深挖账本",
     "sessions · snapshots · hourly quota · deep ledger"),
    ("你的 vault",
     "your vault"),
    (".md 笔记 + 教材",
     ".md notes + handbook"),
    ("OpenAI 兼容",
     "OpenAI-compatible"),
    ("主对话和深挖都从这出去",
     "chat and deep-dive both leave here"),
    ("HTTPS 你填的节点",
     "HTTPS your endpoint"),
    ("你填的节点",
     "your endpoint"),
    ("你的电脑",
     "Your machine"),
    ("只读 → allow，自动过",
     "read-only → allow, automatic"),
    ("改原文 → ask，每次问人",
     "edit → ask, every time"),
    ("其他任何名字",
     "any other name"),
    ("→ deny，一律拒",
     "→ deny, always"),
    ("工具箱只有两把",
     "toolbox has three"),
    ("没有 bash",
     "no bash"),
    ("没有 write_file",
     "no write_file"),
    ("① 沙箱：两套根",
     "① sandbox: two roots"),
    ("写一套，读另一套",
     "one for write, one for read"),
    ("② read-first 硬闸",
     "② read-first hard gate"),
    ("不读就猜，那是江湖骗子干的事",
     "guessing without reading is a con"),
    ("③ 审批面板：你点允许",
     "③ approval panel: you click Allow"),
    ("在此之前磁盘一个字节都没动",
     "until then, not one byte of disk"),
    ("写：只允许这本教材登记",
     "write: only the registered"),
    ("过的那一篇 original_path",
     "handbook original_path"),
    ("读：可放宽到白名单根",
     "read: may widen to a whitelist"),
    (".git · .obsidian · .env* 一律拒",
     ".git · .obsidian · .env* refused"),
    ("必须在更早一轮成功",
     "must have succeeded in an"),
    ("read_file 过同一路径。",
     "earlier turn: same path."),
    ("同一批 tool_calls 里的",
     "Same-batch tool_calls"),
    ("read+edit 也拦——参数是在",
     "read+edit blocked — args were"),
    ("看见读结果之前就定的。",
     "fixed before the read returned."),
    ("面板摆的是 old_string /",
     "the panel shows old_string /"),
    ("new_string 两块 diff，",
     "new_string as a two-block diff;"),
    ("你自己核对完再决定。",
     "you check it, then you decide."),
    ("点「不允许」",
     "click Deny"),
    ("快照入栈 → 写盘",
     "snapshot → write disk"),
    ("undo 栈",
     "undo stack"),
    ("每次写盘前的整篇原文",
     "full note before each write"),
    ("当前这一版",
     "this version"),
    ("redo 栈",
     "redo stack"),
    ("回退时当前篇存这儿",
     "current note parked here on undo"),
    ("你点允许",
     "you click Allow"),
    ("点不允许",
     "on Deny"),
    ("回到上一版",
     "roll back"),
    ("重做时从这弹",
     "redo pops from here"),
    ("GET /v1/sessions/{sid}/deep?since=N",
     "GET /v1/sessions/{sid}/deep?since=N"),
    ("原文",
     "the note"),
    ("落盘",
     "on disk"),
    ("丢",
     "drop"),
]


def translate(src: str) -> str:
    out = src
    for zh, en in sorted(PAIRS, key=lambda p: len(p[0]), reverse=True):
        if zh in out:
            out = out.replace(zh, en)
    return out


def remaining_cjk(text: str) -> list[str]:
    return re.findall(r"[\u4e00-\u9fff]+[^<\"]{0,40}", text)


def mxgraph_ok(svg: str) -> None:
    m = re.search(r"content='([^']*)'", svg) or re.search(r'content="([^"]*)"', svg)
    if not m:
        raise SystemExit("no content= attribute")
    raw = html.unescape(m.group(1))
    ET.fromstring(raw)


def main() -> None:
    names = [
        "arch.drawio.svg",
        "turn.drawio.svg",
        "deep-queue.drawio.svg",
        "writeback.drawio.svg",
        "gates.drawio.svg",
    ]
    failed = False
    for name in names:
        src = ROOT / name
        dest = ROOT / name.replace(".drawio.svg", ".en.drawio.svg")
        text = src.read_text(encoding="utf-8")
        en = translate(text)
        dest.write_text(en, encoding="utf-8")
        cjk = remaining_cjk(en)
        try:
            mxgraph_ok(en)
            xml_ok = True
        except Exception as exc:
            xml_ok = False
            print(f"FAIL xml {name}: {exc}")
            failed = True
        if cjk:
            print(f"CJK leftover in {dest.name}:")
            for s in cjk[:30]:
                print(" ", s)
            if len(cjk) > 30:
                print(f"  … +{len(cjk)-30}")
            failed = True
        else:
            print(f"ok  {dest.name} xml={'yes' if xml_ok else 'no'}")
    raise SystemExit(1 if failed else 0)


if __name__ == "__main__":
    main()
